# Generated by Django 5.0 on 2024-01-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slotbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHECK_IN_DATE', models.DateField(null=True)),
                ('CHECK_OUT_DATE', models.DateField(null=True)),
                ('NUMBER_OF_PERSONS', models.IntegerField(null=True)),
            ],
        ),
    ]
