# Generated by Django 5.0 on 2024-01-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campsiteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotbooking',
            old_name='NUMBER_OF_PERSONS',
            new_name='NUMBER_OF_PERSON',
        ),
    ]
