# Generated by Django 5.0 on 2024-01-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsiteapp', '0002_rename_number_of_persons_slotbooking_number_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='STATUS',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
