# Generated by Django 5.0 on 2024-01-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsiteapp', '0003_slotbooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='guestmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Message', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
